springdoc:
  swagger-ui:
    oauth:
      client-id: spring-app
      use-pkce-with-authorization-code-grant: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:1852/realms/library

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]